---
- project:
    name: openstack-k8s-operators/watcher-operator
    default-branch: main
    templates:
      - opendev-master-watcher-operator-pipeline
    github-check:
      jobs:
        - noop
        - watcher-operator-doc-preview
        - watcher-operator-validation
        - watcher-operator-kuttl

- job:
    name: watcher-operator-base
    parent: podified-multinode-edpm-deployment-crc-2comp
    description: |
      A multinode EDPM Zuul job which has one ansible controller, one
      extracted crc and two computes. It will be used for testing watcher-operator.
    vars:
      cifmw_extras:
        - "@{{ ansible_user_dir }}/{{ zuul.projects['github.com/openstack-k8s-operators/ci-framework'].
           src_dir }}/scenarios/centos-9/multinode-ci.yml"
        - "@{{ ansible_user_dir }}/{{ zuul.projects['github.com/openstack-k8s-operators/ci-framework'].
           src_dir }}/scenarios/centos-9/horizon.yml"
        - "@{{ ansible_user_dir }}/{{ zuul.projects['github.com/openstack-k8s-operators/watcher-operator'].
           src_dir }}/ci/scenarios/edpm.yml"
        - "@{{ ansible_user_dir }}/{{ zuul.projects['github.com/openstack-k8s-operators/watcher-operator'].
           src_dir }}/ci/tests/watcher-master.yml"

- job:
    name: watcher-operator-validation-base
    parent: watcher-operator-base
    abstract: true
    dependencies: ["openstack-meta-content-provider-master"]
    description: |
      A intermediate base job to set config that is needed for jobs running
      in the operator check pipeline but will not be used for other jobs
      inheriting from watcher-operator-base, like the one running in the
      master pipeline.
    vars:
      # Use watcher-tempest-plugin with latest content from master branch
      cifmw_test_operator_tempest_external_plugin:
        - repository: "https://opendev.org/openstack/watcher-tempest-plugin.git"
          changeRepository: "https://review.opendev.org/openstack/watcher-tempest-plugin"
          changeRefspec: "refs/heads/master"
      # Donot use openstack services containers from meta content provider master
      # job.
      cifmw_update_containers_openstack: false
      deploy_watcher_service_extra_vars:
        watcher_catalog_image: "{{ content_provider_registry_ip }}:5001/openstack-k8s-operators/watcher-operator-index:{{ zuul.patchset }}"

- job:
    name: watcher-operator-validation
    parent: watcher-operator-validation-base
    description: |
      A zuul job to validate the watcher operator and its service deployment.
      It will deploy podified and EDPM using current-podified antelope content.
      During watcher deployment, It will fetch master current-podified hash and pull
      openstack watcher services containers from meta content provider.
      It will test current-podified control plane EDPM deployment with openstack watcher
      master content. It deploys watcher using TLSe, and creates the certificates to use.
    extra-vars:
      # Override zuul meta content provider provided content_provider_dlrn_md5_hash
      # var. As returned dlrn md5 hash comes from master release but job is using
      # antelope content.
      content_provider_dlrn_md5_hash: ''
    vars:
      # Donot use openstack services containers from meta content provider master
      # job.
      cifmw_update_containers_openstack: false
      deploy_watcher_service_extra_vars:
        watcher_cr_file: "ci/watcher_v1beta1_watcher_tlse.yaml"

- job:
    name: watcher-operator-kuttl
    dependencies: ["openstack-meta-content-provider-master"]
    parent: cifmw-multinode-kuttl-operator-target
    description: |
      A zuul job to run watcher operator kuttl tests.
      It will pull operator images from meta content provider. There is no
      change in openstack services container images.
    vars:
      # Do not fetch dlrn md5 hash
      fetch_dlrn_hash: false
      deploy_watcher_service_extra_vars:
        watcher_catalog_image: "{{ content_provider_registry_ip }}:5001/openstack-k8s-operators/watcher-operator-index:{{ zuul.patchset }}"
        deploy_watcher_service: false
      cifmw_extras:
        - "@{{ ansible_user_dir }}/{{ zuul.projects['github.com/openstack-k8s-operators/watcher-operator'].
           src_dir }}/ci/scenarios/kuttl.yml"
    extra-vars:
      # Override zuul meta content provider provided content_provider_dlrn_md5_hash
      # var. As returned dlrn md5 hash comes from master release but job is using
      # antelope content.
      content_provider_dlrn_md5_hash: ''
      # We also need to override the registry otherwise kuttl test will fail
      content_provider_os_registry_url: "quay.io/podified-master-centos9"

- job:
    name: watcher-operator-doc-preview
    parent: cifmw-doc
    files:
      - docs
      - Gemfile
    vars:
      asciidoc_available: true
      doc_available: false

##########################################################
#                                                        #
#               Master Zuul Jobs                         #
#                                                        #
##########################################################
- job:
    name: openstack-meta-content-provider-master
    override-checkout: main
    description: |
      A zuul job building content from OpenDev master release.
    parent: openstack-meta-content-provider
    vars:
      cifmw_operator_build_meta_build: false
      cifmw_bop_openstack_release: master
      cifmw_bop_dlrn_baseurl: "https://trunk.rdoproject.org/centos9-master"
      cifmw_repo_setup_branch: master
      cifmw_build_containers_registry_namespace: podified-master-centos9

- job:
    name: watcher-operator-validation-master
    override-checkout: main
    parent: watcher-operator-validation-base
    description: |
      A Zuul job consuming content from openstack-meta-content-provider-master
      and deploying EDPM with master content.
    vars:
      cifmw_repo_setup_branch: master
      # To consume containers from meta content provider
      cifmw_update_containers_openstack: true
      cifmw_update_containers_org: podified-master-centos9

##########################################################
#                                                        #
#               Project Template                         #
#                                                        #
##########################################################

- project-template:
    name: opendev-master-watcher-operator-pipeline
    description: |
      Project template to run meta content provider and
      EDPM job with master opendev and github operator
      content.
    github-check:
      jobs:
        - openstack-meta-content-provider-master
        - watcher-operator-validation-master

- project-template:
    name: opendev-watcher-edpm-pipeline
    description: |
      Project template to run meta content provider and
      EDPM job with master opendev and github operator
      content in openstack-check pipeline.
    openstack-check:
      jobs:
        - openstack-meta-content-provider-master
        - watcher-operator-validation-master
