= User Installation Guide

== Watcher operator installation
The watcher-operator is now integrated in openstack-operator. The
installation of the operator is now part of the installation of the
OpenStack Operator. For details about the deployment consult the
https://openstack-k8s-operators.github.io/openstack-operator/[OpenStack k8s Operators documentation].

== Watcher service deployment

The deployment of the Watcher service is performed as part of the
OpenStackControlplane Custom Resource. A Watcher service section
exist to enable and configure the different aspects of the service.

A default watcher service deployment can be done by just adding
following content to your **OpenStackControlPlane Custom Resource
spec**.

```
  watcher:
    enabled: true
```

For additional details and existing parameters in the watcher service
check the https://openstack-k8s-operators.github.io/openstack-operator/ctlplane/index.html#watchersection[WatcherSection]
and https://openstack-k8s-operators.github.io/openstack-operator/ctlplane/index.html#watcherspeccore[WatcherSpecCore]
sections of the documentation.

**Note:** Watcher requires that the **OpenStackControlPlane** has
Telemetry service enabled, including the MetricStorage system which
provides the Prometheus backend and metrics required by Watcher.
